name: Deploy build
env:
  APP_PATH: /var/app/etherbeam/client

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy build
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Get the Node version
        id: node
        run: echo "::set-output name=NODE_VERSION::$(cat .node-version)"

      - name: Setup Node ${{ steps.node.outputs.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.node.outputs.NODE_VERSION }}'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: '/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --non-interactive

      - name: Create Client .env file
        run: |
          touch .env
          echo SERVER_API_HOST='${{ secrets.SERVER_API_HOST }}' >> .env

      - name: Build distribution
        run: |
          yarn build
          ls -halrt dist

      - name: Copy repository to the VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: '*'
          target: '${{ env.APP_PATH }}'
          rm: true
